import type { ManagedUser } from '@/types/user'

/**
 * Realistic mock staff accounts for User Management Phase 1.
 * Replace with GET /users once the backend endpoint exists.
 */
export const MOCK_MANAGED_USERS: ManagedUser[] = [
  {
    user_id: 1,
    email: 'admin@rrcrc.ca',
    first_name: 'Amina',
    last_name: 'Okafor',
    is_active: true,
    created_at: '2024-01-12T15:00:00Z',
    roles: ['administrator'],
  },
  {
    user_id: 2,
    email: 'jordan.lee@rrcrc.ca',
    first_name: 'Jordan',
    last_name: 'Lee',
    is_active: true,
    created_at: '2024-03-04T10:22:00Z',
    roles: ['staff_editor'],
  },
  {
    user_id: 3,
    email: 'priya.nair@rrcrc.ca',
    first_name: 'Priya',
    last_name: 'Nair',
    is_active: true,
    created_at: '2024-04-18T14:05:00Z',
    roles: ['moderator'],
  },
  {
    user_id: 4,
    email: 'marcus.chen@rrcrc.ca',
    first_name: 'Marcus',
    last_name: 'Chen',
    is_active: true,
    created_at: '2024-05-02T09:40:00Z',
    roles: ['staff_editor'],
  },
  {
    user_id: 5,
    email: 'sofia.martinez@rrcrc.ca',
    first_name: 'Sofia',
    last_name: 'Martinez',
    is_active: true,
    created_at: '2024-02-20T11:15:00Z',
    roles: ['moderator'],
  },
  {
    user_id: 6,
    email: 'daniel.brooks@rrcrc.ca',
    first_name: 'Daniel',
    last_name: 'Brooks',
    is_active: true,
    created_at: '2024-06-11T16:30:00Z',
    roles: ['moderator'],
  },
  {
    user_id: 7,
    email: 'hana.kim@rrcrc.ca',
    first_name: 'Hana',
    last_name: 'Kim',
    is_active: true,
    created_at: '2024-07-01T08:00:00Z',
    roles: ['administrator'],
  },
  {
    user_id: 8,
    email: 'elise.tran@rrcrc.ca',
    first_name: 'Elise',
    last_name: 'Tran',
    is_active: false,
    created_at: '2023-11-08T13:45:00Z',
    roles: ['staff_editor'],
  },
  {
    user_id: 9,
    email: 'owen.patel@rrcrc.ca',
    first_name: 'Owen',
    last_name: 'Patel',
    is_active: true,
    created_at: '2024-08-19T12:10:00Z',
    roles: ['staff_editor'],
  },
  {
    user_id: 10,
    email: 'maya.johnson@rrcrc.ca',
    first_name: 'Maya',
    last_name: 'Johnson',
    is_active: true,
    created_at: '2024-09-03T17:20:00Z',
    roles: ['moderator'],
  },
  {
    user_id: 11,
    email: 'chris.nguyen@rrcrc.ca',
    first_name: 'Chris',
    last_name: 'Nguyen',
    is_active: false,
    created_at: '2024-01-28T10:05:00Z',
    roles: ['administrator'],
  },
  {
    user_id: 12,
    email: 'lena.wright@rrcrc.ca',
    first_name: 'Lena',
    last_name: 'Wright',
    is_active: true,
    created_at: '2025-01-14T09:55:00Z',
    roles: ['moderator'],
  },
]

