services:
  front:
    image: "caddy:2.11-alpine"
    restart: no
    volumes:
      - ./conf/caddy:/etc/caddy:ro # Caddyfile
      - ./front/dist:/usr/share/caddy:ro # Web content
      - caddy-data:/data # Caddy managed data
    ports:
      - 80:80
      - 443:443
      - 443:443/udp

  back:
    build:
      context: back
    stop_signal: SIGINT
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - uploads-data:/app/instance/uploads/resources

  db:
    image: "mysql:8.0-debian"
    command: --sql-mode="TRADITIONAL"
    restart: no
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=1"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - mysql-data:/var/lib/mysql # MySQL DB data

volumes:
  caddy-data:
  mysql-data:
  uploads-data:
