"""Reflect exisitng MySQL RRCRC schema

Revision ID: 471ee9801624
Revises: 
Create Date: 2026-06-15 23:05:32.964182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '471ee9801624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_change_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_change_log_resource'))
        batch_op.drop_index(batch_op.f('idx_change_log_time'))

    op.drop_table('resource_change_log')
    with op.batch_alter_table('resource_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ft_rv_content'), mysql_prefix='FULLTEXT')
        batch_op.drop_index(batch_op.f('idx_rv_resource'))
        batch_op.drop_index(batch_op.f('idx_rv_status'))
        batch_op.drop_index(batch_op.f('idx_rv_submitted_at'))
        batch_op.drop_index(batch_op.f('idx_rv_type'))

    op.drop_table('resource_versions')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('role_name'))

    op.drop_table('roles')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_index(batch_op.f('slug'))

    op.drop_table('tags')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_users_active'))
        batch_op.drop_index(batch_op.f('idx_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_index(batch_op.f('slug'))

    op.drop_table('categories')
    with op.batch_alter_table('resource_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_locations_coords'), mysql_prefix='SPATIAL')
        batch_op.drop_index(batch_op.f('idx_locations_lat_lng'))

    op.drop_table('resource_locations')
    with op.batch_alter_table('resource_version_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_rvt_tag'))

    op.drop_table('resource_version_tags')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_submissions_created'))
        batch_op.drop_index(batch_op.f('idx_submissions_resource'))
        batch_op.drop_index(batch_op.f('idx_submissions_status'))

    op.drop_table('submissions')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_resources_active'))
        batch_op.drop_index(batch_op.f('idx_resources_review_due'))
        batch_op.drop_index(batch_op.f('idx_resources_slug'))
        batch_op.drop_index(batch_op.f('slug'))

    op.drop_table('resources')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_user_role'))

    op.drop_table('user_roles')
    op.drop_table('submission_rate_limits')
    with op.batch_alter_table('resource_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_contacts_version'))

    op.drop_table('resource_contacts')
    with op.batch_alter_table('reported_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_issues_resource'))
        batch_op.drop_index(batch_op.f('idx_issues_status'))

    op.drop_table('reported_issues')
    with op.batch_alter_table('resource_version_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_rvc_category'))

    op.drop_table('resource_version_categories')
    op.drop_table('submission_reviews')
    with op.batch_alter_table('resource_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_hours_version'))
        batch_op.drop_index(batch_op.f('uq_version_day'))

    op.drop_table('resource_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_hours',
    sa.Column('hours_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resource_version_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', mysql.TINYINT(), autoincrement=False, nullable=False, comment='0=Sunday, 1=Monday ... 6=Saturday'),
    sa.Column('opens_at', mysql.TIME(), nullable=True),
    sa.Column('closes_at', mysql.TIME(), nullable=True),
    sa.Column('is_closed', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('by_appointment_only', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('notes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.resource_version_id'], name=op.f('resource_hours_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hours_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resource_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_version_day'), ['resource_version_id', 'day_of_week'], unique=True)
        batch_op.create_index(batch_op.f('idx_hours_version'), ['resource_version_id'], unique=False)

    op.create_table('submission_reviews',
    sa.Column('review_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('submission_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reviewed_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('moderation_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False),
    sa.Column('review_comment', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.user_id'], name=op.f('submission_reviews_ibfk_2'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name=op.f('submission_reviews_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resource_version_categories',
    sa.Column('resource_version_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_primary', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('resource_version_categories_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.resource_version_id'], name=op.f('resource_version_categories_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_version_id', 'category_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resource_version_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rvc_category'), ['category_id'], unique=False)

    op.create_table('reported_issues',
    sa.Column('issue_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resource_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reported_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('reporter_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('reporter_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('issue_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), server_default=sa.text("'open'"), nullable=False),
    sa.Column('resolved_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', mysql.DATETIME(), nullable=True),
    sa.Column('resolution_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.user_id'], name=op.f('reported_issues_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.user_id'], name=op.f('reported_issues_ibfk_3'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name=op.f('reported_issues_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('reported_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_issues_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_issues_resource'), ['resource_id'], unique=False)

    op.create_table('resource_contacts',
    sa.Column('contact_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resource_version_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('contact_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('contact_value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False),
    sa.Column('contact_label', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('is_primary', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.resource_version_id'], name=op.f('resource_contacts_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resource_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_contacts_version'), ['resource_version_id'], unique=False)

    op.create_table('submission_rate_limits',
    sa.Column('ip_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('window_start', mysql.DATETIME(), nullable=False),
    sa.Column('count', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ip_hash', 'window_start'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_roles',
    sa.Column('user_role_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('assigned_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.user_id'], name=op.f('user_roles_ibfk_3'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('user_roles_ibfk_2'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_roles_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_role_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_user_role'), ['user_id', 'role_id'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('token_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('token_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('password_reset_tokens_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('token_hash'), ['token_hash'], unique=True)

    op.create_table('resources',
    sa.Column('resource_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('current_approved_version_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=False),
    sa.Column('is_active', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_verified_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_verified_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('next_review_due_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], name=op.f('resources_ibfk_1'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_approved_version_id'], ['resource_versions.resource_version_id'], name=op.f('fk_resources_current_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_verified_by_user_id'], ['users.user_id'], name=op.f('resources_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('idx_resources_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_resources_review_due'), ['next_review_due_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_resources_active'), ['is_active', 'deleted_at'], unique=False)

    op.create_table('submissions',
    sa.Column('submission_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('submission_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False),
    sa.Column('resource_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('proposed_version_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('submitted_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('submitter_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('submitter_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('submitter_phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('submission_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('moderation_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), server_default=sa.text("'pending_review'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['proposed_version_id'], ['resource_versions.resource_version_id'], name=op.f('submissions_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name=op.f('submissions_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.user_id'], name=op.f('submissions_ibfk_3'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('submission_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_submissions_status'), ['moderation_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_submissions_resource'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_submissions_created'), ['created_at'], unique=False)

    op.create_table('resource_version_tags',
    sa.Column('resource_version_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.resource_version_id'], name=op.f('resource_version_tags_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], name=op.f('resource_version_tags_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_version_id', 'tag_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resource_version_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rvt_tag'), ['tag_id'], unique=False)

    op.create_table('resource_locations',
    sa.Column('location_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resource_version_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('location_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('address_line1', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('address_line2', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), server_default=sa.text("'Ottawa'"), nullable=False),
    sa.Column('province', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'Ontario'"), nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'Canada'"), nullable=False),
    sa.Column('lat', mysql.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('lng', mysql.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('coordinates', sa.NullType(), nullable=False),
    sa.Column('is_primary', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('is_virtual', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('service_area_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.resource_version_id'], name=op.f('resource_locations_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resource_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_locations_lat_lng'), ['lat', 'lng'], unique=False)
        batch_op.create_index(batch_op.f('idx_locations_coords'), ['coordinates'], unique=False, mysql_prefix='SPATIAL')

    op.create_table('categories',
    sa.Column('category_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('icon_identifier', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('color_hex', mysql.CHAR(collation='utf8mb4_unicode_ci', length=7), nullable=True),
    sa.Column('display_order', mysql.SMALLINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.category_id'], name=op.f('categories_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_active'), ['is_active', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('tags',
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('role_name'), ['role_name'], unique=True)

    op.create_table('resource_versions',
    sa.Column('resource_version_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resource_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('resource_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'Organization'"), nullable=False),
    sa.Column('moderation_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), server_default=sa.text("'pending_review'"), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('eligibility', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('cost_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('accessibility_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('general_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('submitted_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('reviewed_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('review_comment', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('approved_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name=op.f('resource_versions_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.user_id'], name=op.f('resource_versions_ibfk_3'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.user_id'], name=op.f('resource_versions_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_version_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resource_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rv_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_rv_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_rv_status'), ['moderation_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_rv_resource'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ft_rv_content'), ['name', 'description'], unique=False, mysql_prefix='FULLTEXT')

    op.create_table('resource_change_log',
    sa.Column('change_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resource_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('change_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('change_summary', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('submission_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('changed_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.user_id'], name=op.f('resource_change_log_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name=op.f('resource_change_log_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name=op.f('resource_change_log_ibfk_3'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('change_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resource_change_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_change_log_time'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_change_log_resource'), ['resource_id'], unique=False)

    # ### end Alembic commands ###
