# docker-compose: local dev configuration
# DO NOT RUN THIS DIRECTLY! Use the Justfile: `just up`
# This will handle environment setup for you

services:
  front:
    image: "caddy:2.11-alpine"
    restart: no
    volumes:
      - ${ROOT}/conf/local/caddy:/etc/caddy:ro # Caddyfile
      - ${ROOT}/front:/usr/share/caddy:ro # Web content
      - capstone-caddy-data:/data # Caddy managed data
    ports:
      - 80:80
      - 443:443
      - 443:443/udp

  # TODO: develop and insert the backend here

  db:
    image: "mysql:8.0-debian"
    command: --sql-mode="TRADITIONAL"
    restart: no
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=1"
    volumes:
      - capstone-mysql-data:/var/lib/mysql # MySQL DB data

volumes:
  capstone-caddy-data:
  capstone-mysql-data:
