"""Initial schema from models.py

Revision ID: 07a113983f84
Revises: 
Create Date: 2026-06-27 21:02:18.904381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07a113983f84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('color_hex',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=7),
               type_=sa.String(length=7),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('reported_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_issues_resource'))
        batch_op.drop_index(batch_op.f('idx_issues_status'))

    with op.batch_alter_table('resource_change_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_change_log_resource'))
        batch_op.drop_index(batch_op.f('idx_change_log_time'))

    with op.batch_alter_table('resource_contacts', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('idx_contacts_version'))

    with op.batch_alter_table('resource_hours', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment=None,
               existing_comment='0=Sunday, 1=Monday ... 6=Saturday',
               existing_nullable=False)
        batch_op.alter_column('is_closed',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('by_appointment_only',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('idx_hours_version'))

    with op.batch_alter_table('resource_locations', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('is_virtual',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('idx_locations_lat_lng'))
        batch_op.drop_column('coordinates')

    with op.batch_alter_table('resource_version_categories', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('idx_rvc_category'))

    with op.batch_alter_table('resource_version_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_rvt_tag'))

    with op.batch_alter_table('resource_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ft_rv_content'), mysql_prefix='FULLTEXT')
        batch_op.drop_index(batch_op.f('idx_rv_resource'))
        batch_op.drop_index(batch_op.f('idx_rv_status'))
        batch_op.drop_index(batch_op.f('idx_rv_submitted_at'))
        batch_op.drop_index(batch_op.f('idx_rv_type'))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_index(batch_op.f('idx_resources_active'))
        batch_op.drop_index(batch_op.f('idx_resources_review_due'))
        batch_op.drop_index(batch_op.f('idx_resources_slug'))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_submissions_created'))
        batch_op.drop_index(batch_op.f('idx_submissions_resource'))
        batch_op.drop_index(batch_op.f('idx_submissions_status'))

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_index(batch_op.f('idx_users_active'))
        batch_op.drop_index(batch_op.f('idx_users_email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_active'), ['is_active', 'deleted_at'], unique=False)
        batch_op.alter_column('is_active',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_submissions_status'), ['moderation_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_submissions_resource'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_submissions_created'), ['created_at'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_resources_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_resources_review_due'), ['next_review_due_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_resources_active'), ['is_active', 'deleted_at'], unique=False)
        batch_op.alter_column('is_active',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('resource_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rv_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_rv_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_rv_status'), ['moderation_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_rv_resource'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ft_rv_content'), ['name', 'description'], unique=False, mysql_prefix='FULLTEXT')

    with op.batch_alter_table('resource_version_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rvt_tag'), ['tag_id'], unique=False)

    with op.batch_alter_table('resource_version_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rvc_category'), ['category_id'], unique=False)
        batch_op.alter_column('is_primary',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('resource_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.NullType(), nullable=True))
        batch_op.create_index(batch_op.f('idx_locations_lat_lng'), ['lat', 'lng'], unique=False)
        batch_op.alter_column('is_virtual',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_primary',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('resource_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_hours_version'), ['resource_version_id'], unique=False)
        batch_op.alter_column('by_appointment_only',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_closed',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('day_of_week',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='0=Sunday, 1=Monday ... 6=Saturday',
               existing_nullable=False)

    with op.batch_alter_table('resource_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_contacts_version'), ['resource_version_id'], unique=False)
        batch_op.alter_column('is_primary',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('resource_change_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_change_log_time'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_change_log_resource'), ['resource_id'], unique=False)

    with op.batch_alter_table('reported_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_issues_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_issues_resource'), ['resource_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('color_hex',
               existing_type=sa.String(length=7),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=7),
               existing_nullable=True)

    # ### end Alembic commands ###
